### ISSUE TITLE
Could not auto scroll to correct line after `Lrc` resized ?

### ISSUE THREAD

**Issue by mebtte** [mebtte/react-lrc#1]
i don't know how to inspect Lrc resize, if you know how please tell me, thanks very much.

**Comment by Brandhsu** [comment]
Hi nice project!
I was wondering how your demo has autoscroll, I tried the example lyrics.js and can't seem to get autoscroll working.

**Comment by mebtte** [comment]
@Brandhsu Could you give me a demo like `codesandbox` ?

**Comment by Brandhsu** [comment]
Sure I sent.

**Comment by mebtte** [comment]
using ResizeObserver to detect lrc size change.
