### ISSUE TITLE
[FR] qrc和krc（逐字歌词）支持

### ISSUE THREAD

**Issue by lovegaoshi** [mebtte/react-lrc#18]
您好！
我在用react-native端移植的这个代码库，加入了逐字歌词qrc（qq）和krc（kugou）支持，并且有兴趣将改动移植回react库下和使用。我会提交PR.
https://github.com/lovegaoshi/react-native-lyric/pulls?q=is%3Apr+is%3Aclosed

**Comment by mebtte** [comment]
`react-lrc` 底层使用的是 [clrc](https://github.com/mebtte/clrc) 进行解析, 正如这两个库的名字一样, `clrc` 和 `react-lrc` 只专注于 LRC 格式, 暂时不会考虑其他格式.
我这边更建议你新建一个仓库, 类似于 `react-lyric` 来实现其他格式的解析和展示.
