### ISSUE TITLE
automatic scrolling status

### ISSUE THREAD

**Issue by KUNKUN2121** [mebtte/react-lrc#20]
Hello.
Thank you for the very useful framework.

I want to stop scrolling when the user wants to scroll, but I want an event that fires at that time.

I would like to display the automatic scrolling resume button only when automatic scrolling is disabled.

**Comment by mebtte** [comment]
You can prevent user-scroll like this:
```
const style = { overflow: 'hidden !important' };
<Lrc style={style} recoverAutoScrollInterval={0} {...otherProps} />;
```

**Comment by KUNKUN2121** [comment]
Rather than prevent scrolling, I would like to display button [recover auto scroll immediately] only when the user scrolls.

**Comment by mebtte** [comment]
react-lrc@3.2.0 has released, and there is a `onAutoScrollChange`, which indicates whether or not it is auto-scroll.

**Comment by KUNKUN2121** [comment]
Thank you so much.
I have created the program we envisioned.

**Comment by mebtte** [comment]
> It doesn't work on my smartphone, do you know the cause?

Currently browser can not verify that scroll is [from user or script](https://stackoverflow.com/questions/7035896/detect-whether-scroll-event-was-created-by-user), so `react-lrc` uses a [hack way](https://github.com/mebtte/react-lrc/blob/master/src/components/base_lrc/use_auto_scroll.ts) to detect. It relys on mouse event, but there is no mouse event on smarkphone. Maybe I should change mouse event to pointer event.

**Comment by mebtte** [comment]
Please use [3.2.1](https://www.npmjs.com/package/react-lrc/v/3.2.1)
