### ISSUE TITLE
Can i using lineRender to control everylinenode's before-avtive, active, after-active

### ISSUE THREAD

**Issue by outishacker26** [mebtte/react-lrc#5]
大意是我想利用您的套件，將active後的字變成灰色，active前的字變成與背景同色，而正在active的是綠色，這功能在目前的套件中辦得到嗎？ 我剛學前端，還很多不懂，所以特地鼓起勇氣發問，我研究了好一陣子，不知道調整lineRender這個回呼函示是否就能辦到？ 想要問您是否有一些example code能引導一下我，感謝您，這對我來說意義非凡。

**Comment by mebtte** [comment]
@outishacker26 通过 `onLineUpdate` 记录当前的 `index`, 然后和 `lineRenderer` 中的 `index` 对比实现不同的样式, 这是个[例子](https://codesandbox.io/s/5-iz1xgr)
https://codesandbox.io/s/5-iz1xgr

**Comment by outishacker26** [comment]
謝謝你，這條路上非常高興認識你
