### ISSUE TITLE
lrc 元件放到除了Root元件之外的地方，滾動會失效

### ISSUE THREAD

**Issue by outishacker26** [mebtte/react-lrc#6]
如題，我嘗試單獨使用lrc元件，發現可以正常渲染line顏色，但是滾動和verticalSpace會同時失效，想問問要怎麼修改才能生效？
我想放到一個table body 裡面，這會是因為table的關係嗎？
調查之後發現，是外層必須有position absolute 和 display flex和 height 100%，不知道能不能在不需要用到absoult的狀況下實現這種滾動呢？ @mebtte 
以下是復現例子：
https://codesandbox.io/s/5-forked-oqdfeq

**Comment by mebtte** [comment]
@outishacker26 请提供一下复现的例子

**Comment by outishacker26** [comment]
以更新問題，提供復現例子

**Comment by outishacker26** [comment]
更新，發現外層沒有Root，verticalSpace和滾動會同時失效

**Comment by mebtte** [comment]
@outishacker26 https://codesandbox.io/s/5-forked-oqdfeq 这个例子没有发现相关问题
![image](https://user-images.githubusercontent.com/8120967/224489412-c93d758d-629f-420f-bf55-d9bd99ffc967.png)

**Comment by mebtte** [comment]
@outishacker26 通常情况下产生这个问题的原因在于 `Lrc` 组件没有确定的高度(not auto), 从而无法产生滚动条

**Comment by outishacker26** [comment]
剛剛在測試所以改動到了代碼，我更新這版，把root拿掉之後，就失效了，為了排版我現在的配置如連結內。https://codesandbox.io/s/5-forked-vebt98?file=/src/app.tsx  再麻煩看看一下，因為absoulute 的設定常常會超出預期範圍，所以要如何放在外層沒有absoulute的情況下呢？

**Comment by outishacker26** [comment]
喔喔對了，可以新增verticalspace的option嗎？修改空白的大小％數 @mebtte

**Comment by mebtte** [comment]
https://codesandbox.io/s/5-forked-vebt98?file=/src/app.tsx 你这个例子是因为滚动条不是 Lrc 产生的
所以 Lrc 无法滚动, 你需要调整你的 CSS 让 Lrc 产生滚动条才能自动滚动以及 `verticalSpace` 生效

**Comment by mebtte** [comment]
> 喔喔對了，可以新增verticalspace的option嗎？修改verticalSpace的大小％數 @mebtte

暂时没有这种应用场景, 而且 `verticalSpace` 是上下各 50%, 如果改成可调整数值的话则会变成两个参数

**Comment by outishacker26** [comment]
> > 喔喔對了，可以新增verticalspace的option嗎？修改verticalSpace的大小％數 @mebtte
> 
> 暂时没有这种应用场景, 而且 `verticalSpace` 是上下各 50%, 如果改成可调整数值的话则会变成两个参数

嗯嗯，在我的應用場景中，上下的space能調整的話會很棒，可以利用option的改概念在vertical space內接收一個物件(option)，video.js是這樣設計的

**Comment by outishacker26** [comment]
> https://codesandbox.io/s/5-forked-vebt98?file=/src/app.tsx 你这个例子是因为滚动条不是 Lrc 产生的 所以 Lrc 无法滚动, 你需要调整你的 CSS 让 Lrc 产生滚动条才能自动滚动以及 `verticalSpace` 生效

OK，感謝你，最後用了absoulte自己計算％數讓他不跑版

**Comment by outishacker26** [comment]
不過在理論上有辦法把lrc外層產生滾動條的元素包裝進去lrc中嗎？ @mebtte

**Comment by mebtte** [comment]
> 不過在理論上有辦法把lrc外層產生滾動條的元素包裝進去lrc中嗎？套件打包進去的意思，因為這樣就能直接單獨取用元件，這樣比較開箱即用 @mebtte

这是无法实现的, 在 CSS 的角度子节点是无法修改父节点的样式的

**Comment by outishacker26** [comment]
好的，感謝您，或許要往其他方向approach。問題已經解決了，我先關閉囉
