### ISSUE TITLE
Current Lyric not visible when when Lrc is too small

### ISSUE THREAD

**Issue by lonelil** [mebtte/react-lrc#9]
When the Lrc component is too small, the current lyric will be off screen.

10 rem:
![image](https://user-images.githubusercontent.com/51315646/236475779-2ff38f00-faa6-4183-b810-0e8c3fc6d635.png)

15 rem:
![image](https://user-images.githubusercontent.com/51315646/236475947-16f779ed-b30b-4cda-a961-d00321190355.png)

**Comment by mebtte** [comment]
Please provide a minimal demo that can reproduce.
